Added action setting to build release package

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,8 +2,8 @@ name: Release
 
 on:
   push:
-    branches:
-      - main
+    tags:
+      - "v*"
 
 jobs:
   release:
@@ -13,18 +13,19 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Extract version from tag
-        if: startsWith(github.ref, 'refs/tags/v')
         run: |
-          VERSION=${GITHUB_REF#refs/tags/v}
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          if [[ $GITHUB_REF =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
+            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
+          else
+            echo "Invalid tag format. Skipping release."
+            exit 1
+          fi
 
       - name: Update version in Cargo.toml
-        if: startsWith(github.ref, 'refs/tags/v')
         run: |
-          sed -i 's/version = ".*"/version = "$VERSION"/' Cargo.toml
+          sed -i 's/^version = ".*"/version = "$VERSION"/' Cargo.toml
 
       - name: Commit and push changes
-        if: startsWith(github.ref, 'refs/tags/v')
         run: |
           git config --local user.email "claudioropez.k@gmail.com"
           git config --local user.name "Kazunori Osaki"
@@ -32,13 +33,17 @@ jobs:
           git commit -m "Update version to $VERSION"
           git push origin main
 
+      - name: Build release package
+        run: |
+          cargo build --release
+
       - name: Create release
-        if: startsWith(github.ref, 'refs/tags/v')
-        uses: actions/create-release@v1
+        uses: softprops/action-gh-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ github.ref }}
-          release_name: Release ${{ github.ref }}
+          name: Release ${{ github.ref }}
           draft: false
           prerelease: false
+          files: target/release/pcc
